import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  Copy,
  CreditCard,
  Database,
  Edit,
  Emergency,
  FileText,
  Github,
  HelpCircle,
  Layers,
  Loader2,
  Lock,
  Logout,
  Mail,
  Menu,
  MessageSquare,
  Moon,
  Plus,
  RotateCw,
  Settings,
  Share2,
  Shield,
  SunMedium,
  Trash,
  User,
  PlusCircle,
  X,
  ExternalLink,
  Eye,
  EyeOff,
  Download,
  Upload,
  Calendar,
  Bell,
  Book,
  ClipboardList,
  LucideIcon,
} from "lucide-react"

const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  circle: Circle,
  copy: Copy,
  creditCard: CreditCard,
  database: Database,
  edit: Edit,
  emergency: Emergency,
  fileText: FileText,
  github: Github,
  helpCircle: HelpCircle,
  layers: Layers,
  loader2: Loader2,
  lock: Lock,
  logout: Logout,
  mail: Mail,
  menu: Menu,
  messageSquare: MessageSquare,
  moon: Moon,
  plus: Plus,
  rotateCw: RotateCw,
  settings: Settings,
  share: Share2,
  shield: Shield,
  sun: SunMedium,
  trash: Trash,
  user: User,
  close: X,
  add: PlusCircle,
  back: ArrowLeft,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  download: Download,
  upload: Upload,
  calendar: Calendar,
  bell: Bell,
  book: Book,
  clipboardList: ClipboardList,
}

export default Icons;

import * as lucide from "lucide-react";

// Add the QrCode icon
export const QrCode = lucide.QrCode;
