
import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  Copy,
  CreditCard,
  Database,
  Edit,
  FileText,
  Github,
  HelpCircle,
  Layers,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Moon,
  Plus,
  RotateCw,
  Settings,
  Share2,
  Shield,
  SunMedium,
  Trash,
  User,
  PlusCircle,
  X,
  ExternalLink,
  Eye,
  EyeOff,
  Download,
  Upload,
  Calendar,
  Bell,
  Book,
  ClipboardList,
  Mic,
  QrCode,
  FileText2,
  LucideIcon,
} from "lucide-react"

const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  circle: Circle,
  copy: Copy,
  creditCard: CreditCard,
  database: Database,
  edit: Edit,
  emergency: FileText2, // Using FileText2 as a substitute for Emergency since it doesn't exist
  fileText: FileText,
  github: Github,
  helpCircle: HelpCircle,
  layers: Layers,
  loader2: Loader2,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  messageSquare: MessageSquare,
  moon: Moon,
  plus: Plus,
  rotateCw: RotateCw,
  settings: Settings,
  share: Share2,
  shield: Shield,
  sun: SunMedium,
  trash: Trash,
  user: User,
  close: X,
  add: PlusCircle,
  back: ArrowLeft,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  download: Download,
  upload: Upload,
  calendar: Calendar,
  bell: Bell,
  book: Book,
  clipboardList: ClipboardList,
  voice: Mic, // Using Mic for Voice
  reset: RotateCw, // Using RotateCw for Reset
  medicalRecords: FileText, // Using FileText for MedicalRecords
  spinner: Loader2, // Using Loader2 for Spinner
  qrCode: QrCode,
}

export default Icons;
